### ISSUE TITLE
Отчёт по задаче #4 DevOps - Ansible: роли, переменные и группы хостов

### ISSUE THREAD

**Issue by Batiscafff** [role-forge/devops-4#1]
### 1. Ansible роль c именем [nginx](https://github.com/role-forge/nginx)
Вся информация по роли находится в ее репо, роль была протестированна на пустом сервере с данным плейбуком.
 ```yaml
- name: Настройка Nginx и управление SSL сертификатами
  hosts: all
  vars:
    nginx_letsencrypt_cert:
      - batiscaf-emo-students.devboxops.xyz
    nginx_selfsigned_cert:
      - batiscaf-emo-proxied-students.devboxops.xyz
    nginx_letsencrypt_cert_renewal: true
    nginx_vhosts:
      - batiscaf-emo-students.devboxops.xyz
      - batiscaf-emo-proxied-students.devboxops.xyz
  roles:
    - nginx
```
После его выполнения все настройки были выполнены успешно:

![image](https://github.com/role-forge/devops-4/assets/168472804/45643ea9-5c22-4e18-839c-945ca4c0c26a)

![image](https://github.com/role-forge/devops-4/assets/168472804/57a53818-1527-49d3-8719-29b3db5583bd)

### 2. Ansible роль с именем [user](https://github.com/role-forge/user)
Вся информация по роли находится в ее репо, роль была протестированна на пустом сервере с данными плейбуками.
 ```yaml
- name: Make user
  hosts: all
  vars:
    user_name: dev-user
    user_sudo: true
    user_password: "passwd"
    user_ssh_key:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC56o5lpxITIoDWYU6/Otv/cSQ3d5odBf0jM6PhmW0+cKRU8oNxaDQrbkcWhLvhOKRqbmo1+HOux14DQN/30Kzs5JX93t/>
    user_sudoers:
      - /bin/systemctl start systemd-journald
      - /bin/systemctl stop systemd-journald
  roles:
    - role: user 
```

```yaml
- name: Make user
  hosts: all
  vars:
    user_name: prod-user
    user_sudo: false
    user_password: "passwd1"
    user_ssh_key:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC56o5lpxITIoDWYU6/Otv/cSQ3d5odBf0jM6PhmW0+cKRU8oNxaDQrbkcWhLvhOKRqbmo1+HOux14DQN/30Kzs5JX93t/>
    user_sudoers:
      - /bin/systemctl stop rsyslog
      - /bin/systemctl start rsyslog
  roles:
    - role: user 
```
После их выполнения все настройки были выполнены успешно:
![image](https://github.com/role-forge/devops-4/assets/168472804/3a747fb1-5882-4535-b108-e4af99470954)

![image](https://github.com/role-forge/devops-4/assets/168472804/f221f02d-b44d-4bf3-8e59-bf198351ef5a)
